set -o pipefail;set -x;{ { set +x; } 2>/dev/null && echo 'echo "line 1: failed test output on stdout"' \# 'RUN: at line 3' >&2 && { set -x; } 2>/dev/null && {   echo "line 1: failed test output on stdout"; }; } &&
{ { set +x; } 2>/dev/null && echo 'echo "line 2: failed test output on stdout"' \# 'RUN: at line 4' >&2 && { set -x; } 2>/dev/null && {   echo "line 2: failed test output on stdout"; }; } &&
{ { set +x; } 2>/dev/null && echo 'cat "does-not-exist"' \# 'RUN: at line 5' >&2 && { set -x; } 2>/dev/null && {   cat "does-not-exist"; }; }
